server:
  port: 10000
spring.application.name: miya-item-web

#\u6CE8\u518C\u670D\u52A1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8888/eureka/            #\u672C\u5730\u8FD0\u884C
#      defaultZone: http://eureka-server:8888/eureka/      #docker\u73AF\u5883\u8FD0\u884C\uFF0C\u7528docker --link\u6765\u624B\u52A8\u6307\u5B9Aeureka-server\u7684\u5177\u4F53\u5730\u5740


#spring:
#  zipkin:
#    base-url: http://localhost:10000   #\u8DDF\u8E2A\u670D\u52A1\u670D\u52A1\u5668\u7684\u5730\u5740


#\u8C03\u7528\u5176\u4ED6\u670D\u52A1
feign.hystrix.enabled: true



spring:
  mvc.static-path-pattern: /static/**   #\u8BBE\u5B9A\u9759\u6001\u6587\u4EF6\u8DEF\u5F84\uFF0Cjs,css\u7B49

  #freemarker -- start
  freemarker:
    template-loader-path: classpath:/templates/ftl  #\u8BBE\u5B9Aftl\u6587\u4EF6\u8DEF\u5F84
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  #freemarker -- end