#图片服务的url
IMAGE_SERVER_URL: http://10.106.204.12


#FTP相关配置
#FTP的ip地址
FTP_ADDRESS: 192.168.25.133
FTP_PORT: 21
FTP_USERNAME: ftpuser
FTP_PASSWORD: ftpuser
FTP_BASE_PATH: /home/ftpuser/www/images
#图片服务器的相关配置
#图片服务器的基础url
IMAGE_BASE_URL: http://192.168.25.133/images
#
##服务层基础url
REST_BASE_URL: http://192.168.25.136:8080/rest
REST_CONTENT_SYNC_URL: /cache/sync/content/



spring.datasource:
   continue-on-error: false # Do not stop if an error occurs while initializing the database.
   initialize: false # Populate the database using 'data.sql'.
   jmx-enabled: false # Enable JMX support (if provided by the underlying pool).
   name: dataSource # Name of the datasource.
   type: 'com.zaxxer.hikari.HikariDataSource'
   driver-class-name: 'com.mysql.jdbc.Driver'
   url: 'jdbc:mysql://localhost:3306/taotao?useUnicode=true&characterEncoding=utf-8&useSSL=true'
#   url: 'jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf-8'
   username: root
   password: 123456
   max-active: 100
   max-idle: 8
   min-idle: 8
   test-while-idle: true
   time-between-eviction-runs-millis: 1
   validation-query: 'SELECT 1'

server:
  port: 8001


